version: '3.1'
services:

    mysql:
        image: mysql
        ports:
            - 5432:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: blog
